{{- if .Values.cloudwatchObservabilityAddOn.enabled }}
# This ClusterRoleBinding grants the cloudwatch-agent service account permissions
# needed for the CloudWatch Observability add-on
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudwatch-agent-role-binding
  labels:
    k8s-app: cloudwatch-agent
    app: {{ .Values.fluentBit.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudwatch-agent-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.fluentBit.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
---
# This ClusterRole grants the necessary permissions to the cloudwatch-agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudwatch-agent-role
  labels:
    k8s-app: cloudwatch-agent
    app: {{ .Values.fluentBit.name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes/stats", "configmaps", "events"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["cwagent-clusterleader"]
    verbs: ["get", "update"]
{{- end }} 