apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fluentBit.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    k8s-app: {{ .Values.fluentBit.name }}
data:
  fluent-bit.conf: |-
{{ .Files.Get "conf/fluent-bit.conf" | indent 4 }}
  application-log.conf: |-
{{ .Files.Get "conf/application-log.conf" | indent 4 }}
  dataplane-log.conf: |-
{{ .Files.Get "conf/dataplane-log.conf" | indent 4 }}
  host-log.conf: |-
{{ .Files.Get "conf/host-log.conf" | indent 4 }}
  parsers.conf: |-
{{ .Files.Get "conf/parsers.conf" | indent 4 }} 