{{- if .Values.fluentBit.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentBit.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.fluentBit.name }}
{{- end }} 