# Default values for fluent-bit
# This is a YAML-formatted file.

# AWS region and cluster name for CloudWatch logs
aws:
  region: ap-northeast-1
  clusterName: "demo-eks-cluster"

# Namespace to deploy Fluent Bit resources
namespace:
  name: amazon-cloudwatch
  create: false
  labels:
    name: amazon-cloudwatch

# Fluent Bit configuration
fluentBit:
  name: fluent-bit
  image:
    repository: public.ecr.aws/aws-observability/aws-for-fluent-bit
    tag: 2.32.5.20250327
    pullPolicy: Always
  
  env:
    readFromHead: "Off"
    readFromTail: "On"
    ciVersion: "k8s/1.3.31"

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
      
  # Service account configuration
  serviceAccount:
    # If true, create a new service account
    create: true
    # If not creating one, the name of the service account to use
    name: cloudwatch-agent
    
  # Node selector
  nodeSelector:
    "kubernetes.io/os": linux
    
  # Pod configuration
  pod:
    terminationGracePeriodSeconds: 10
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

  # Tolerations
  tolerations: []
  
  # Labels for the fluent-bit deployment
  labels:
    k8s-app: fluent-bit
    version: v1
    kubernetes.io/cluster-service: "true"

# Paths for various logs and state directories
paths:
  fluentBitState: /var/fluent-bit/state
  varLog: /var/log
  dockerContainers: /var/lib/docker/containers
  runLogJournal: /run/log/journal
  dmesg: /var/log/dmesg 


# EKS addon for cloudwatch-observability
cloudwatchObservabilityAddOn:
  # Enable or disable the EKS add-on for amazon-cloudwatch-observability
  enabled: true
  # Role ARN for the service account used by the CloudWatch agent
  # Required if enabled is true
  serviceAccountRoleArn: "arn:aws:iam::1234567890:role/cloudwatch-observability-demo-eks-cluster"
  # If creating a new IAM role via eksctl or other tools
  createRole: false
  # Only relevant if createRole is true - sets policy attachments
  rolePolicyArns:
    - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
  # Add-on configuration options
  addOnConfig:
    conflictResolution: "OVERWRITE"
    resolveConflictsOnCreate: "OVERWRITE"
    resolveConflictsOnUpdate: "OVERWRITE"
